name: Update Wiki

# on: [push]

# recommended
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ineshbose/wiki-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIKI_DIR: 'docs'
          AUTO_SIDEBAR: true
