name: Update Wiki

# on: [push]

# recommended
on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tirazel/ghaction-wiki-docs-publish@v1
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
